import PDFDocument from 'pdfkit';

export const generateLeasePDF = (tenant, property) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    let buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => resolve(Buffer.concat(buffers)));

    // --- Header ---
    doc.fillColor('#4f46e5').fontSize(20).text('GRANDNUM PROPERTIES', { align: 'right' });
    doc.fillColor('#444').fontSize(10).text('Management & Real Estate', { align: 'right' });
    doc.text('Nairobi, Kenya', { align: 'right' });
    doc.moveDown();

    // --- Title ---
    doc.fillColor('#333').fontSize(18).text('RESIDENTIAL LEASE AGREEMENT', { underline: true });
    doc.moveDown();

    // --- Section 1: Parties ---
    doc.fontSize(12).fillColor('#4f46e5').text('1. THE PARTIES');
    doc.fillColor('#333').fontSize(10).text(`Tenant Name: ${tenant.firstname} ${tenant.lastname}`);
    doc.text(`ID / KRA PIN: ${tenant.idnumber} / ${tenant.kraPin || 'N/A'}`);
    doc.text(`Occupation: ${tenant.occupation || 'N/A'}`);
    doc.moveDown();

    // --- Section 2: Premises ---
    doc.fontSize(12).fillColor('#4f46e5').text('2. THE PREMISES');
    doc.fillColor('#333').fontSize(10).text(`Property Name: ${property?.propertyname || 'As Assigned'}`);
    doc.text(`Location: ${property?.location || 'Nairobi'}`);
    doc.moveDown();

    // --- Highlight Box (Lease Term) ---
    doc.rect(50, doc.y, 500, 50).fill('#f3f4f6');
    doc.fillColor('#4f46e5').text('LEASE DURATION', 60, doc.y + 10, { stroke: true });
    doc.fillColor('#333').text(`Commencement: ${tenant.leasestarts} | Termination: ${tenant.leaseends}`, 60, doc.y + 15);
    doc.moveDown(4);

    // --- Section 3: Terms ---
    doc.fontSize(12).fillColor('#4f46e5').text('3. CORE TERMS & CONDITIONS');
    doc.fillColor('#333').fontSize(9).text('• RENT: Due on the 1st of every month.', { bulletRadius: 2 });
    doc.text('• MAINTENANCE: Tenant shall maintain the interior in a clean state.');
    doc.text('• TERMINATION: One full month notice is required before vacating.');
    
    // --- Footer ---
    doc.fontSize(8).fillColor('#999').text(
      `Generated by Grandnum System on ${new Date().toLocaleDateString()}`, 
      50, 780, { align: 'center' }
    );

    doc.end();
  });
};

// Add to src/utils/pdfGenerator.js

export const generateLandlordPDF = (landlord) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    let buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => resolve(Buffer.concat(buffers)));

    // --- Header ---
    doc.fillColor('#4f46e5').fontSize(22).text('GRANDNUM PROPERTIES', { align: 'right' });
    doc.fillColor('#444').fontSize(10).text('Management & Real Estate Solutions', { align: 'right' });
    doc.text('Nairobi, Kenya', { align: 'right' });
    doc.moveDown(2);

    // --- Title ---
    doc.fillColor('#333').fontSize(18).text('PROPERTY MANAGEMENT AGREEMENT', { underline: true });
    doc.moveDown();

    // --- Section 1: Parties ---
    doc.fontSize(12).fillColor('#4f46e5').text('1. PARTIES');
    doc.fillColor('#333').fontSize(10).text(`Landlord: ${landlord.firstname} ${landlord.lastname}`);
    doc.text(`ID Number: ${landlord.idnumber}`);
    doc.text(`Address: ${landlord.address || 'Not Provided'}`);
    doc.moveDown();

    // --- Highlight Box (Commission & Period) ---
    doc.rect(50, doc.y, 500, 60).fill('#f3f4f6');
    doc.fillColor('#4f46e5').text('AGREEMENT SUMMARY', 60, doc.y + 10, { stroke: true });
    doc.fillColor('#333').text(`Management Commission: ${landlord.commision}% of Gross Revenue`, 60, doc.y + 15);
    doc.text(`Effective Period: ${landlord.agreement_start} to ${landlord.agreement_end}`, 60, doc.y + 10);
    doc.moveDown(4);

    // --- Section 2: Remittance ---
    doc.fontSize(12).fillColor('#4f46e5').text('2. PAYMENT REMITTANCE');
    doc.fillColor('#333').fontSize(10).text('Funds (less commission) shall be sent to:');
    doc.text(`Bank Name: ${landlord.bankname}`);
    doc.text(`Account Number: ${landlord.bankaccountnumber}`);
    doc.moveDown();

    // --- Section 3: Terms ---
    doc.fontSize(12).fillColor('#4f46e5').text('3. TERMS & CONDITIONS');
    doc.fillColor('#333').fontSize(9).text('• The Agent is authorized to advertise, vet tenants, and collect rent.');
    doc.text('• The Landlord agrees to maintain the structural integrity of the property.');
    doc.text('• Termination requires 30 days written notice from either party.');

    // --- Signature Area ---
    doc.moveDown(4);
    doc.fontSize(10).text('__________________________          __________________________', { align: 'center' });
    doc.text('For: Grandnum Properties              Landlord Signature', { align: 'center' });

    doc.end();
  });
};

// Add to src/utils/pdfGenerator.js

export const generatePaymentReceiptPDF = (payment, tenant, property) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    let buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => resolve(Buffer.concat(buffers)));

    // --- Header ---
    doc.fillColor('#4f46e5').fontSize(22).text('GRANDNUM PROPERTIES', { align: 'right' });
    doc.fillColor('#444').fontSize(10).text('Official Payment Receipt', { align: 'right' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });
    doc.moveDown();

    // --- Receipt Number ---
    doc.fillColor('#333').fontSize(14).text(`RECEIPT NO: GNM-PAY-${payment.id.toString().padStart(5, '0')}`);
    doc.moveDown();

    // --- Section: Payment Details ---
    doc.rect(50, doc.y, 500, 100).stroke('#eee');
    const startY = doc.y + 10;
    doc.fontSize(10).fillColor('#666').text('RECEIVED FROM:', 60, startY);
    doc.fillColor('#000').fontSize(12).text(`${tenant.firstname} ${tenant.lastname}`, 60, startY + 15);
    
    doc.fontSize(10).fillColor('#666').text('PROPERTY:', 300, startY);
    doc.fillColor('#000').fontSize(11).text(`${property?.propertyname || 'N/A'}`, 300, startY + 15);
    doc.moveDown(5);

    // --- Table Header ---
    const tableTop = doc.y;
    doc.rect(50, tableTop, 500, 25).fill('#4f46e5');
    doc.fillColor('#fff').fontSize(10).text('Description', 60, tableTop + 8);
    doc.text('Method', 250, tableTop + 8);
    doc.text('Reference', 350, tableTop + 8);
    doc.text('Amount (KSH)', 450, tableTop + 8);

    // --- Table Row ---
    doc.fillColor('#000').text(payment.paymenttype || 'Rent Payment', 60, tableTop + 35);
    doc.text(payment.paymentmethod || 'M-Pesa', 250, tableTop + 35);
    doc.text(payment.reference || 'N/A', 350, tableTop + 35);
    doc.fontSize(12).font('Helvetica-Bold').text(`${Number(payment.amount).toLocaleString()}`, 450, tableTop + 35);

    // --- Total Box ---
    doc.moveDown(4);
    doc.rect(350, doc.y, 200, 40).fill('#f9fafb');
    doc.fillColor('#4f46e5').fontSize(12).text('TOTAL PAID:', 360, doc.y - 30);
    doc.fillColor('#000').text(`KSH ${Number(payment.amount).toLocaleString()}`, 460, doc.y - 30);

    // --- Status Stamp ---
    doc.fontSize(30).fillColor('#22c55e').opacity(0.2).text('PAID', 400, 150, { rotation: -15 });
    doc.opacity(1);

    // --- Footer ---
    doc.fontSize(9).fillColor('#999').text(
      'This is an electronically generated receipt. No signature is required.', 
      50, 780, { align: 'center' }
    );

    doc.end();
  });
};

export const generateInvoicePDF = (tenant, property) => {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    let buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => resolve(Buffer.concat(buffers)));

    // Branding
    doc.fillColor('#4f46e5').fontSize(20).text('GRANDNUM PROPERTIES', { align: 'right' });
    doc.fillColor('#444').fontSize(10).text('Monthly Rental Invoice', { align: 'right' });
    doc.moveDown();

    // Tenant Details
    doc.fontSize(12).fillColor('#111').text('BILL TO:', { underline: true });
    doc.text(`${tenant.firstname} ${tenant.lastname}`);
    doc.text(`Unit: ${property.propertyname} (${property.housenumber})`);
    doc.moveDown();

    // Billing Table
    const tableTop = 200;
    doc.fontSize(10).text('Description', 50, tableTop);
    doc.text('Amount (KSH)', 400, tableTop);
    doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();

    let y = tableTop + 30;
    
    // Rent Row
    doc.text('Monthly Rent', 50, y);
    doc.text(property.rentamount.toLocaleString(), 400, y);
    
    // --- PLACEHOLDERS FOR FUTURE FIELDS ---
    y += 20; doc.text('Arrears:', 50, y); doc.text('---', 400, y);
    y += 20; doc.text('Water Bill / Units:', 50, y); doc.text('---', 400, y);
    y += 20; doc.text('Service Charge / Garbage:', 50, y); doc.text('---', 400, y);
    // ---------------------------------------

    doc.moveTo(50, y + 20).lineTo(550, y + 20).stroke();
    doc.fontSize(14).text(`TOTAL DUE: KSH ${property.rentamount.toLocaleString()}`, 350, y + 35);

    // Footer Account Details
    doc.fontSize(10).fillColor('#666').text('PAYMENT INSTRUCTIONS:', 50, 700);
    doc.text('Please pay to: [Insert Account/Paybill Here]', 50, 715);
    doc.text('Rent is due by the 5th of every month.', 50, 730);

    doc.end();
  });
};